backend:
    name: git-gateway
    branch: main
media_folder: public/images
public_folder: images
collections:
    - name: "pages"
      label: "Pages"
      files:
          - label: "About"
            name: "about"
            file: "content/about.md"
            fields:
                - { label: "Title", name: "title", widget: "string" }
                - { label: "Body", name: "body", widget: "markdown" }
